#!/usr/bin/env sh

BRANCH=$(git branch --show-current)

if [ "$BRANCH" = "develop" ]; then
  COUNT=$(git rev-list --count HEAD)
  if [ "$COUNT" -eq 1 ]; then
    printf "\n"
    printf "Create a PR to merge develop into main:\n"
    printf "https://github.com/joserogeriofilho/printable-booklet-app/compare/main...develop?expand=1\n"
    printf "\n"
  fi
fi
